Repository wpmudev/hustle-ui, pull requests merged in 2019-09, with the labels that each got.

#46 [Timepicker] Fix dropdown showing outside the view at the bottom
  library/js/timepicker.full.js
Labels: enhancement

#44 Fix closing with esc key not working as expected
  library/js/popup-close.js
  library/js/slidein-close.js
Labels: bug

#45 Receive translated strings for datepicker
  library/js/datepicker.js
Labels: enhancement

#47 Order of errors on front is incorrect
  library/js/optin-error.js
Labels: bug, enhancement
